language: node_js
node_js:
  - '10'
before_install:
  - npm i -g now
before_script:
  - cd client
  - npm i
  - npx jest --version
script: 'npm run test:ci -- --ci'
deploy:
  skip_cleanup: true
  provider: script
  script: now --token=$NOW_TOKEN --target production
  on:
    branch: master
