language: node_js
node_js:
  - '10'
before_install:
  - npm i -g now
script: ./test.sh
deploy:
  skip_cleanup: true
  provider: script
  script: now --token=$NOW_TOKEN --target production
  on:
    branch: master
