language: node_js
node_js:
  - '10'
before_install:
  - export TZ=Australia/Canberra
  - npm i -g npm@'>=6.9.0'
  - npm i -g now
before_script:
  - cd client
  - npm i
  - npx jest --version
script: 'npm run test:ci -- --ci'
before_deploy:
  - cd ..
deploy:
  skip_cleanup: false
  provider: script
  script: now --token=$NOW_TOKEN --target production && now alias
  on:
    branch: master
